pipeline {
    agent {
        kubernetes {
            label 'kaniko'
        }
    }
    environment {
        APP_NAME = 'alerts-worker' 
        SRC_PATH = './src/alerts-worker'
        DOCKER_REPO = 'sirroastedpotato'
    }
    stages {
        stage('Check Changes') {
            steps {
                script {
                    if (currentBuild.previousBuild == null) {
                        echo "First build detected, skipping change detection."
                    } else {
                        def changes = sh(script: "git diff HEAD~1 --name-only | grep -E '^src/alerts-worker/'", returnStatus: true)
                        
                        if (changes != 0) {
                            echo "No changes in src/alerts-worker/, skipping build."
                            currentBuild.result = 'SUCCESS'
                            error('Pipeline stopped: No changes detected.')
                        }
                    }
                }
            }
        }
        stage('Build & Push') {
            steps {
                container('kaniko') {
                    sh """
                    /kaniko/executor \
                    --context=${WORKSPACE}/${SRC_PATH} \
                    --dockerfile=${WORKSPACE}/${SRC_PATH}/Dockerfile \
                    --destination=${DOCKER_CREDS_USR}/${APP_NAME}:${BUILD_NUMBER}
                    """
                }
            }
        }
        stage('Deploy') {
            steps {
                sh "sed -i 's|image: .*:.*|image: ${DOCKER_CREDS_USR}/${APP_NAME}:${env.BUILD_NUMBER}|g' infrastructure/YAML/${APP_NAME}-deployment.yaml"
                git config user.name "Jenkins"
                git config user.email "jenkins@example.com"
                sh "git commit -am 'Update ${APP_NAME} to ${env.BUILD_NUMBER}'"
                sh "git push origin main"
            }
        }
    }
}