apiVersion: batch/v1
kind: CronJob
metadata:
  name: job-scraper
  namespace: data-pipeline
spec:
  # Schedule: Runs every 5 minutes
  schedule: "*/5 * * * *" 
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: scraper
            image: job-scraper:v1
            # Look inside Kind instead of DockerHub
            imagePullPolicy: Never 
            env:
            - name: KAFKA_BROKER
              value: "my-kafka-kafka-bootstrap:9092"
          restartPolicy: OnFailure