pipeline {
    agent any
    environment {
        DOCKER_CREDS = credentials('dockerhub')
        APP_NAME = 'digest-worker' 
        SRC_PATH = './src/digest-worker'
        CHANGES_DETECT = 'false'
    }
    stages {
        stage('Check Changes') {
            steps {
                script {
                    if (currentBuild.previousBuild == null) {
                        echo "First build detected. Proceeding to initialize baseline."
                        env.CHANGES_DETECTED = 'true'
                    } else {
                        def exitCode = sh(
                            script: "git diff HEAD~1 --name-only | grep -E '^${SRC_PATH}/'",
                            returnStatus: true
                        )
                        
                        if (exitCode == 0) {
                            echo "Changes detected in directory ${SRC_PATH}!"
                            env.CHANGES_DETECTED = 'true'
                        } else {
                            echo "No changes found in directory ${SRC_PATH}."
                            env.CHANGES_DETECTED = 'false'
                        }
                    }
                }
            }
        }
        stage('Docker Login') {
            steps {
                script {
                    sh "echo ${DOCKER_CREDS_PSW} | docker login -u ${DOCKER_CREDS_USR} --password-stdin"
                }
            }
        }
        stage('Build') {
            steps {
                sh "docker build -t ${DOCKER_CREDS_USR}/${APP_NAME}:${env.BUILD_NUMBER} ${SRC_PATH}"
            }
        }
        stage('Push') {
            steps {
                sh "docker push ${DOCKER_CREDS_USR}/${APP_NAME}:${env.BUILD_NUMBER}"
            }
        }
        stage('Deploy') {
            steps {
                sh "sed -i 's|image: .*:.*|image: ${DOCKER_CREDS_USR}/${APP_NAME}:${env.BUILD_NUMBER}|g' infrastructure/YAML/${APP_NAME}-deployment.yaml"
                sh "git commit -am 'Update ${APP_NAME} to ${env.BUILD_NUMBER}'"
                sh "git push origin main"
            }
        }
    }
}