pipeline {
    agent {
        // Kaniko builder
        kubernetes {
            yaml '''
            apiVersion: v1
            kind: Pod
            spec:
              containers:
              - name: kaniko
                image: gcr.io/kaniko-project/executor:debug
                command: ["sleep"]
                args: ["9999999"]
              - name: jnlp
                image: jenkins/inbound-agent:latest
            '''
        }
    }
    environment {
        DOCKER_CREDS     = credentials('dockerhub')
        APP_NAME         = 'digest-worker' 
        SRC_PATH         = 'src/digest-worker'
        CHANGES_DETECTED = 'false'
    }
    stages {
        stage('Check Changes') {
            steps {
                script {
                    if (currentBuild.previousBuild == null) {
                        echo "First build detected. Proceeding to initialize baseline."
                        env.CHANGES_DETECTED = 'true'
                    } else {
                        def exitCode = sh(
                            script: "git diff HEAD~1 --name-only | grep -E '^${SRC_PATH}/'",
                            returnStatus: true
                        )
                        
                        if (exitCode == 0) {
                            echo "Changes detected in directory ${SRC_PATH}!"
                            env.CHANGES_DETECTED = 'true'
                        } else {
                            echo "No changes found in directory ${SRC_PATH}."
                            env.CHANGES_DETECTED = 'false'
                        }
                    }
                }
            }
        }
        
        stage('Build and Push') {
            when {
                environment name: 'CHANGES_DETECTED', value: 'true'
            }
            steps {
                container('kaniko') {
                    script {
                        // 1. Authenticate with Docker Hub
                        sh '''
                            AUTH=$(echo -n "${DOCKER_CREDS_USR}:${DOCKER_CREDS_PSW}" | base64 | tr -d '\\n')
                            mkdir -p /kaniko/.docker
                            echo "{\\"auths\\":{\\"https://index.docker.io/v1/\\":{\\"auth\\":\\"${AUTH}\\"}}}" > /kaniko/.docker/config.json
                        '''
                        // 2. Build and Push the image
                        sh "/kaniko/executor --context `pwd`/${SRC_PATH} --dockerfile `pwd`/${SRC_PATH}/Dockerfile --destination ${DOCKER_CREDS_USR}/${APP_NAME}:${env.BUILD_NUMBER}"
                    }
                }
            }
        }
        
        stage('Deploy') {
            when {
                environment name: 'CHANGES_DETECTED', value: 'true'
            }
            steps {
                sh "sed -i 's|image: .*:.*|image: ${DOCKER_CREDS_USR}/${APP_NAME}:${env.BUILD_NUMBER}|g' infrastructure/YAML/${APP_NAME}-deployment.yaml"
                sh "git config user.email 'jenkins@example.com'"
                sh "git config user.name 'Jenkins'"
                sh "git add infrastructure/YAML/${APP_NAME}-deployment.yaml"
                sh "git commit -m 'Update ${APP_NAME} to ${env.BUILD_NUMBER}' || echo 'No manifest modifications needed'"
                sh "git push origin main"
            }
        }
    }
}