pipeline {
    agent any
    environment {
        DOCKER_CREDS = credentials('dockerhub')
        APP_NAME = 'digest-worker' 
        SRC_PATH = './src/digest-worker'
    }
    stages {
        stage('Check Changes') {
            steps {
                script {
                    def changed = sh(
                        script: "git diff HEAD~1 --name-only | grep '^src/digest-worker/' || true",
                        returnStdout: true
                    ).trim()

                    if (!changed) {
                        echo "No changes in src/digest-worker. Skipping build."
                        return
                    }
                }
                    }
                }
        }
        stage('Docker Login') {
            steps {
                script {
                    sh "echo ${DOCKER_CREDS_PSW} | docker login -u ${DOCKER_CREDS_USR} --password-stdin"
                }
            }
        }
        stage('Build') {
            steps {
                sh "docker build -t ${DOCKER_CREDS_USR}/${APP_NAME}:${env.BUILD_NUMBER} ${SRC_PATH}"
            }
        }
        stage('Push') {
            steps {
                sh "docker push ${DOCKER_CREDS_USR}/${APP_NAME}:${env.BUILD_NUMBER}"
            }
        }
        stage('Deploy') {
            steps {
                sh "sed -i 's|image: .*:.*|image: ${DOCKER_CREDS_USR}/${APP_NAME}:${env.BUILD_NUMBER}|g' infrastructure/YAML/${APP_NAME}-deployment.yaml"
                sh "git commit -am 'Update ${APP_NAME} to ${env.BUILD_NUMBER}'"
                sh "git push origin main"
            }
        }
    }
}